// <auto-generated />
namespace OpenDagAppBackEnd.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class EditAnswerModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditAnswerModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201308082123301_EditAnswerModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
