// <auto-generated />
namespace OpenDagAppBackEnd.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class removeStudyInformationId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeStudyInformationId));
        
        string IMigrationMetadata.Id
        {
            get { return "201310051238017_removeStudyInformationId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
