// <auto-generated />
namespace OpenDagAppBackEnd.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class booleanWholeDay : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(booleanWholeDay));
        
        string IMigrationMetadata.Id
        {
            get { return "201310211011228_booleanWholeDay"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
